services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: keepi_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "ProdPassword123"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql


  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keepi_web
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=db;Database=keepi_prod;User=sa;Password=ProdPassword123"
    ports:
      - "5000:5000"
    volumes:
      - sql_data:/var/opt/mssql
volumes:
  db_data:
    name: keepi_db_data
      - "1433:1433"
