version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=keepi_prod;User=sa;Password=ProdPassword123
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    volumes:
      - ./Logs:/app/Logs # שמירת לוגים
      - ./wwwroot:/app/wwwroot # אחסון סטטי מותאם אישית
    restart: always # הבטחה שהשירות יופעל מחדש במקרה של קריסה

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: keepi_prod_db
    environment:
      SA_PASSWORD: "ProdPassword123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql # שמירת נתוני הדאטהבייס
    restart: always # הבטחה שהשירות יופעל מחדש במקרה של קריסה

volumes:
  db_data: # ווליום לשמירת נתוני הדאטהבייס

